# 使用官方 Go 镜像作为构建环境
FROM golang:1.22 as builder

# 设置工作目录
WORKDIR /app

# 设置 Go 模块代理
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

# 将当前目录下的所有文件复制到工作目录中
COPY . .

# 下载依赖并构建可执行文件
RUN go mod tidy
RUN sh make.sh

# 使用一个更小的镜像来运行应用程序
FROM alpine:3.15

# 更换 APK 镜像源
RUN sed -i 's|http://dl-cdn.alpinelinux.org|https://mirrors.aliyun.com/alpine|g' /etc/apk/repositories

# 更新包源并安装 ca-certificates
RUN apk update && apk --no-cache add ca-certificates

# 设置工作目录
WORKDIR /root/

# 从构建环境中复制可执行文件到当前镜像
COPY --from=builder /app/bin/keep-online .

# 执行应用程序
CMD ["./keep-online help"]
